---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: container-registry
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    cert-manager.io/common-name: registry.nubes.local
#    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
#    nginx.ingress.kubernetes.io/proxy-ssl-protocols: "TLSv1.3"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: public
spec:
  tls:
    - hosts:
      - registry.nubes.local
      secretName: registry-cert
  rules:
    - host: registry.nubes.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: registry
                port:
                  number: 5000
#  ingressClassName: nginx