apiVersion: secrets.nubes.wolkenschloss.github.com/v1
kind: DbSecretGenerator
metadata:
  name: notImportantHere
  annotations:
    config.kubernetes.io/function: |
      container:
        image: nubes/generators/db-secret-generator
spec:
  template:
    name: db-secret
    user: admin