apiVersion: v1
kind: ConfigMap
metadata:
  name: dex-config
data:
  config.yml: |
    issuer: https://dex.wolkenschloss.test
    
    storage:
      type: sqlite3
      config:
        file: /var/dex/dex.db
    
    web:
      http: 0.0.0.0:5556
    
    telemetry:
      http: 127.0.0.1:5558
    
    grpc:
      addr: 127.0.0.1:5557
    
    staticClients:
      - id: example-app
        redirectURIs:
          - 'http://127.0.0.1:5555/callback'
        name: 'Example App'
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    oauth2:
      responseTypes: ["code", "token", "id_token"]
    connectors:
      - type: mockCallback
        id: mock
        name: Example
    
    enablePasswordDB: true
    
    staticPasswords:
      - email: "admin@example.com"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
        username: "admin"
        userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
