quarkus:
  log:
    level: INFO
  container-image:
    push: true
  kubernetes:
    annotations:
      "linkerd.io/inject": enabled
  mongodb:
    connection-string: mongodb://admin:password@mongodb:27017/?uuidRepresentation=STANDARD