quarkus:
  docker:
    dockerfile-jvm-path: ./src/docker/Dockerfile.jvm
  container-image:
    group: nubes
    name: cookbook
    tag: latest
  http:
    port: 8180
    access-log:
      enabled: true
  mongodb:
    database: cookbook
    devservices:
      properties:
        uuidRepresentation: STANDARD
  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c] %s%e%n"
    category:
      "org.mongodb.driver":
        level: WARN
      "io.quarkus.deployment.**":
        level: ERROR
  arc:
    exclude-types: familie.haschka.wolkenschloss.cookbook.testing.*,*Testcase,ThrowingConsumer,*Fixture,*Test$*
  config:
    locations:
      - project.properties
"%prod":
   quarkus:
     mongodb:
       connection-string: mongodb://${HOST:localhost}:27017/?uuidRepresentation=STANDARD

"%dev":
   quarkus:
     http:
       port: 8180

"%test":
  quarkus:
    http:
      port: 0
      test-port: 9292
    log:
      level: INFO
