quarkus:
  docker:
    dockerfile-jvm-path: ./src/docker/Dockerfile.jvm
#  native:
#    builder-image: quay.io/quarkus/ubi-quarkus-native-image:21.3-java17
#  container-image:
#    name: cookbook
#    tag: latest
#    push: false
#    insecure: true
#    build: true
#  jib:
#    ports: 8180
#    base-jvm-image: "quay.io/quarkus/ubi-quarkus-native-image:21.2.0-java16"
#    base-jvm-image: "fabricate/java-alpine-openjdk11-jre"
  http:
    port: 8180
    access-log:
      enabled: true

  mongodb:
    database: cookbook
    connection-string: mongodb://${HOST:localhost}:27017/?uuidRepresentation=STANDARD
    devservices:
      properties:
        uuidRepresentation: STANDARD
  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c] %s%e%n"
    category:
      "org.mongodb.driver":
        level: WARN
      "io.quarkus.deployment.**":
        level: ERROR
wolkenschloss:
  nubes:
    testhost: ${HOST:localhost}

"%dev":
   quarkus:
     http:
       port: 8180

"%test":
  quarkus:
    http:
      port: 0
      test-port: 9292
    log:
      level: INFO
    mongodb:
      devservices:
        enabled: false
