quarkus:
  log:
    level: INFO
  container-image:
    push: true
  kubernetes-config:
    secrets:
      enabled: true
  kubernetes:
    env:
      secrets: [db-secret]
      mapping:
        quarkus-mongodb-credentials-username:
          from-secret: db-secret
          with-key: username
        quarkus-mongodb-credentials-password:
          from-secret: db-secret
          with-key: password
  mongodb:
    hosts:
      - mongodb
    credentials:
      auth-source: admin