quarkus:
  http:
    port: 8180
  mongodb:
    database: cookbook
    connection-string: mongodb://localhost:27017/?uuidRepresentation=STANDARD
  log:
    level: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c] %s%e%n"
      color: true
    category:
      "org.mongodb.driver":
        level: WARN
      "io.quarkus.deployment.**":
        level: ERROR

"%dev":
   quarkus:
     http:
       port: 8180
   mongodb:
     database: cookbook
     connection-string: mongodb:localhost:27017/?uuidRepresentation=STANDARD
"%test":
  quarkus:
    http:
      port: 0
    log:
      level: INFO