---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb-standalone
      annotations:
        linkerd.io/inject: enabled
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-standalone
          image: mongo:4.0.10
          ports:
            - containerPort: 27017
              name: mongodb-port
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: db-secret
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: db-secret
                  optional: false
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: microk8s-hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017
      name: mongodb-port
