---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cookbook-ingress
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    cert-manager.io/common-name: cookbook.wolkenschloss.local
    kubernetes.io/ingress.class: public
spec:
  tls:
    - hosts:
        - cookbook.wolkenschloss.local
      secretName: cookbook-cert
  rules:
    - host: cookbook.wolkenschloss.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: cookbook
                port:
                  name: http