apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-istio
resources:
  - namespace.yml
  - ../../services
patchesStrategicMerge:
  - gateway.yml
generators:
  - db-secret.yml