name: Verify Issue

on:
  pull_request:
    types:
      - edited
      - synchronize
      - opened
      - reopened
  check_run:

jobs:
  verify-linked-issue:
    runs-on: ubuntu-latest
    name: Ensure Pull Request has a linked issue.
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
